Proj 1 vector operations
RomanLetsuk/made-cpp-2020-hw pull request #3
Opened 2020-10-05 21:43 UTC by RomanLetsuk

2020-10-17 13:17 UTC, SweetWeakness requested changes

2020-10-17 13:17 UTC, SweetWeakness commented on vector_operations/src/vector_ops.cpp
> +    for (size_t i = 0; i < size; i++) {
size используется один раз в цикле - почему бы сразу не засунуть это туда?

2020-10-17 13:17 UTC, SweetWeakness commented on vector_operations/src/vector_ops.cpp
> +        return false;
а если обе координаты 0?
например вектора
0 1 1 и 0 1 1 сонаправлены

2020-10-17 13:17 UTC, SweetWeakness commented on vector_operations/src/vector_ops.cpp
> +      ? a[0] / b[0] > 0
опять так на ноль можем поделить

2020-10-17 13:17 UTC, SweetWeakness commented on vector_operations/src/vector_ops.cpp
> +      swap(&a[i], &a[size - i - 1]);
вот это сильно)
нет смысла передавать ссылки в функцию
я так понимаю вы хотели передать в функцию сами объекты а не их копию
но тогда

2020-10-17 13:17 UTC, SweetWeakness commented on vector_operations/src/vector_ops.cpp
> +}
надо принимать по ссылке здесь, чтобы не происходило копирование и вы работали с самими аргументами а не с их копиями

т.е. (double &a, double &b) - означает что a и b в функции будут ТЕМИ a и b которые были переданы (и не надо ничего разыменовывать)

2020-10-17 13:17 UTC, SweetWeakness commented on vector_operations/src/vector_ops.cpp
> +      swap(&a[i], &a[size - i - 1]);
https://ru.stackoverflow.com/questions/484078/%D0%9F%D0%B5%D1%80%D0%B5%D0%B4%D0%B0%D1%87%D0%B0-%D0%B2-%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D1%8E-%D1%83%D0%BA%D0%B0%D0%B7%D0%B0%D1%82%D0%B5%D0%BB%D1%8F-%D0%B8%D0%BB%D0%B8-%D1%81%D1%81%D1%8B%D0%BB%D0%BA%D0%B8

2020-10-19 15:50 UTC, RomanLetsuk commented on vector_operations/src/vector_ops.cpp
> +    for (size_t i = 0; i < size; i++) {
О каком одном разе вы говорите? Если использовать метод size в условии цикла for метод size будет вызываться после каждой итерации

2020-10-29 01:22 UTC, merged