Hw 4 matrix
RomanLetsuk/made-cpp-2020-hw pull request #5
Opened 2020-10-13 20:57 UTC by RomanLetsuk

2020-10-29 01:26 UTC, Costello1329 reviewed
[Line 251] Matrix operator * / *=

2020-10-29 01:26 UTC, Costello1329 requested changes
.

2020-11-01 12:43 UTC, RomanLetsuk commented
> .

@Costello1329 Исправил

2020-11-01 15:47 UTC, Costello1329 commented
Так, ну ладно, поставим вам дробный балл и примем.

2020-11-01 15:48 UTC, merged