Hw 5 chuck allocator
RomanLetsuk/made-cpp-2020-hw pull request #7
Opened 2020-10-27 19:07 UTC by RomanLetsuk

2020-10-29 01:22 UTC, Costello1329 requested changes

2020-10-29 01:22 UTC, Costello1329 commented on chuck_allocator/src/chunk_allocator.cpp
> +  int linksCount;
Это и не нужно.

2020-10-29 01:22 UTC, Costello1329 commented on chuck_allocator/src/chunk_allocator.cpp
> +  const int maxSize = 1024;
Лучше в static const size_t вынести

2020-10-29 01:22 UTC, Costello1329 commented on chuck_allocator/src/chunk_allocator.cpp
> +  const int maxSize = 1024;
И вообще откуда int??? У вас size_type есть, спросите его у аллокатора.

2020-10-29 01:22 UTC, Costello1329 commented on chuck_allocator/src/chunk_allocator.cpp
> +  int currentPointer = 0;
опять int...

2020-10-29 01:22 UTC, Costello1329 commented on chuck_allocator/src/chunk_allocator.cpp
> +      throw "Unpossible allocate memory";
Не-не, std::bad_alloc().

PS: "Unpossible allocate memory" – вообще не по правилам английского языка. Лучше: "Can not allocate requested amount of memory."

2020-10-29 01:22 UTC, Costello1329 commented on chuck_allocator/src/chunk_allocator.cpp
> +    new (p) T(args...);
std::forward

2020-10-29 01:22 UTC, Costello1329 commented on chuck_allocator/src/chunk_allocator.cpp
> +    auto currentChunk = chunks;
n * sizeof(T) – вынести в переменную-константу в функции

2020-11-01 20:16 UTC, RomanLetsuk commented
@Costello1329 Исправил.

2020-11-03 23:53 UTC, merged